added missing include to TraversibilityMap3d.cpp
To fix this error:

```
TraversabilityMap3d.cpp:88:16: error: ‘visited’ was not declared in this scope
                 if(visited.find(neighbor) != visited.end())
```